
# GCC Layer needed to install Spruce

FROM gcc:9.2 AS build

# Install Cmake and Boost

RUN apt-get -qq update && \
    apt-get -qq install --no-install-recommends \
        wget \
        cmake \
        libgtest-dev \
        libboost-all-dev && \
    apt-get clean

# Install LEMON

RUN wget http://lemon.cs.elte.hu/pub/sources/lemon-1.3.1.tar.gz && \
    tar xvf lemon-1.3.1.tar.gz && \
	cd lemon-1.3.1 && \
    mkdir build && cd build && \
    cmake .. && make && make install

# Install SPRUCE (commit e5ffc8)

RUN git clone https://github.com/raphael-group/spruce.git && \
    cd spruce && \
    git checkout e5ffc8 && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make

RUN cd /



# Ubuntu base libraries

FROM ubuntu:20.04

ENV HOME=/home/dockeruser
RUN mkdir /home/dockeruser && \
    touch /home/dockeruser/.bashrc && \
    chmod -R 777 /home/dockeruser 

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH

COPY . phyloflow

RUN apt-get -qq update
RUN apt-get -qq install --no-install-recommends \
        curl \
        iproute2 \
        bzip2 \
        ca-certificates \
        git \
        sudo \
        gnupg2 \
        lxc \
        xvfb \
        ssh \
        vim \
        wget \
        gzip \
        libltdl7 \
        tree \
        ;

RUN apt-get clean

# Anaconda environments

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py37_4.9.2-Linux-x86_64.sh  -O ~/miniconda.sh

RUN /bin/bash ~/miniconda.sh -b -p /opt/conda
RUN rm ~/miniconda.sh
RUN ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh
RUN echo ". /opt/conda/etc/profile.d/conda.sh" >> /home/dockeruser/.bashrc
RUN echo "conda activate base" >> /home/dockeruser/.bashrc

RUN conda config --add channels bioconda
RUN conda config --add channels conda-forge

# PARSL

RUN conda create -n parsl-env \
    --file /phyloflow/parsl/requirements.txt --yes
RUN conda clean --all --yes
RUN conda list

# VCF

RUN conda create -n vcf-transform \
    --file /phyloflow/vcf_transform/requirements.txt --yes
RUN conda clean --all --yes
RUN conda list

# Pyclone Vi

RUN conda create -n pyclone-vi \
    --file /phyloflow/pyclone_vi/requirements.txt --yes
RUN conda clean --all --yes
RUN conda list

# Cluster Transform

RUN conda create -n cluster-transform \
    --file /phyloflow/cluster_transform/requirements.txt --yes
RUN conda clean --all --yes
RUN conda list

# Spruce

COPY --from=build /usr/local/include /usr/local/include
RUN mkdir spruce
COPY --from=build spruce/build spruce

# Aggregate

RUN conda create -n aggregate-json \
    --file /phyloflow/aggregate_json/requirements.txt --yes
RUN conda clean --all --yes
RUN conda list

